# Generated by Django 3.2.4 on 2021-06-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория крафта')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория крафта(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CraftIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория крафта')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория крафта(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/craft_items/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='CraftSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория крафта')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория крафта(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название предмета')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название предмета(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/items/', verbose_name='Изображение')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('bop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рарность')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рарность(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название слота')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название слота(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тира')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тира(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название типа')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название типа(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.craftingredient')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemcategory', verbose_name='Категория '),
        ),
        migrations.AddField(
            model_name='item',
            name='crafted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.craftcategory', verbose_name='Категория крафта'),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemrarity', verbose_name='Тир'),
        ),
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemslot', verbose_name='Слот'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='item',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemtier', verbose_name='Тир'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.itemtype', verbose_name='Тип'),
        ),
    ]
