# Generated by Django 3.2.4 on 2021-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gear_score',
            field=models.IntegerField(default=0, verbose_name='ГС'),
        ),
    ]
