# Generated by Django 3.2.4 on 2021-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_gear_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gear_score',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
