# Generated by Django 3.2.4 on 2021-06-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210606_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/craft_items/', verbose_name='Изображение')),
                ('tier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория ')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название слота')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название слота(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название типа')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название типа(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemRarity',
        ),
        migrations.DeleteModel(
            name='ItemTier',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.resourcecategory', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='resource',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.resourceslot', verbose_name='Слот'),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.resourcetype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.resource'),
        ),
        migrations.DeleteModel(
            name='CraftIngredient',
        ),
    ]
