# Generated by Django 3.2.4 on 2021-08-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210809_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='block_stability',
        ),
        migrations.AddField(
            model_name='item',
            name='icon_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
