# Generated by Django 3.2.4 on 2021-08-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210809_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerkAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perk',
            name='is_perk_with_attributes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ItemPerkAttribute',
        ),
        migrations.AddField(
            model_name='perkattribute',
            name='perk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perk_attributes', to='item.perk', verbose_name='Перк'),
        ),
    ]
