# Generated by Django 3.2.4 on 2021-08-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20210809_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weightClass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
