# Generated by Django 3.2.4 on 2021-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_item_weightclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='item.ItemSubCategory', verbose_name='Податегории'),
        ),
    ]
