# Generated by Django 3.2.4 on 2021-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210617_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
