# Generated by Django 3.2.4 on 2021-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_guide_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
