# Generated by Django 3.2.4 on 2021-07-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guide_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-created_at']},
        ),
    ]
