# Generated by Django 3.2.4 on 2021-07-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_alter_guide_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecategory',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
