# Generated by Django 3.2.4 on 2021-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_guidecategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'ordering': ['order']},
        ),
    ]
