# Generated by Django 3.2.4 on 2021-06-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/poi/', verbose_name='Изображение')),
                ('level', models.IntegerField(default=0)),
                ('x_game', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('x_map', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('y_game', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('y_map', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('lng', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория ')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/resource/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название(оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('level', models.IntegerField(default=0)),
                ('x_game', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('x_map', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('y_game', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('y_map', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('lng', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.resourcecategory', verbose_name='Тип')),
            ],
        ),
    ]
