# Generated by Django 3.2.4 on 2021-06-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210607_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_slug',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='x_game',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='x_map',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='y_game',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='y_map',
        ),
    ]
