# Generated by Django 3.2.4 on 2021-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210607_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория ')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='type',
            field=models.ManyToManyField(blank=True, to='map.ResourceType'),
        ),
    ]
