# Generated by Django 3.2.4 on 2021-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210607_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['name_en']},
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
