# Generated by Django 3.2.4 on 2021-06-08 06:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='marker_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет'),
        ),
    ]
