# Generated by Django 3.2.4 on 2021-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20210611_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
