# Generated by Django 3.2.4 on 2021-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_resource_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='description_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
