# Generated by Django 3.2.4 on 2021-07-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20210726_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='x_game',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='x_map',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='y_game',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='y_map',
        ),
        migrations.AlterField(
            model_name='poi',
            name='image',
            field=models.ImageField(blank=True, upload_to='poi/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
