# Generated by Django 3.2.4 on 2021-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_post_postitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
