# Generated by Django 3.2.4 on 2021-07-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postitem',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
