# Generated by Django 3.2.4 on 2021-09-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postitem',
            options={'ordering': ['-created_at']},
        ),
    ]
