# Generated by Django 3.2.4 on 2021-07-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210705_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialitem',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='socialitem',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
