# Generated by Django 3.2.4 on 2021-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_url_for_site',
            field=models.BooleanField(default=False, verbose_name='cссылка с баннера на другой сайт?'),
        ),
    ]
