# Generated by Django 3.2.4 on 2021-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banner_is_url_for_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='socialitem',
            name='url',
        ),
        migrations.AddField(
            model_name='socialitem',
            name='url_twitch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка твич'),
        ),
        migrations.AddField(
            model_name='socialitem',
            name='url_youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка ютуб'),
        ),
    ]
