# Generated by Django 3.2.4 on 2021-08-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reciperecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='main_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='craft.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='reciperecipe',
            name='main_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_recipe', to='craft.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='craft.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craft.item', verbose_name='Игридиент'),
        ),
        migrations.AlterField(
            model_name='reciperecipe',
            name='recipe_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='craft.recipe', verbose_name='Игридиент Рецепт'),
        ),
    ]
