# Generated by Django 3.2.4 on 2021-08-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0002_auto_20210806_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='main_recipe',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craft.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='craft.item', verbose_name='Игридиент'),
        ),
    ]
