# Generated by Django 3.2.4 on 2021-08-08 09:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0003_auto_20210806_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название англ'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название англ'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название англ'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/craft/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/craft/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/craft/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='craft.item', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='reciperecipe',
            name='recipe_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='craft.recipe', verbose_name='Ингридиент Рецепт'),
        ),
    ]
