# Generated by Django 3.2.4 on 2021-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
