# Generated by Django 3.2.4 on 2021-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_guild_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='server',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
