# Generated by Django 3.2.4 on 2021-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_guild_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='discord_link',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
