# Generated by Django 3.2.4 on 2021-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_alter_guild_discord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='style',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
