# Generated by Django 3.2.4 on 2021-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_auto_20210614_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
