# Generated by Django 3.2.4 on 2021-07-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_guild_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildfeedback',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='guild.guild'),
        ),
    ]
