# Generated by Django 3.2.4 on 2021-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210624_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guild_member',
            field=models.BooleanField(default=False),
        ),
    ]
