# Generated by Django 3.2.4 on 2021-06-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/weapon/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория ')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/resource/', verbose_name='Изображение')),
                ('is_checked', models.BooleanField(default=False)),
                ('is_can_check', models.BooleanField(default=False)),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.skill', verbose_name='Относится к')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.weapon', verbose_name='Оружие')),
            ],
        ),
    ]
