# Generated by Django 3.2.4 on 2021-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
