# Generated by Django 3.2.4 on 2021-06-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20210608_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_ultimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='main_char',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
