# Generated by Django 3.2.4 on 2021-06-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20210608_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='weapon',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/skill/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (оригинал)')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.weapon', verbose_name='Ветка')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.skilltree', verbose_name='Оружие'),
        ),
    ]
