# Generated by Django 3.2.4 on 2021-06-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_auto_20210608_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/skill/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (оригинал)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='parent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.skill', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.skilltree', verbose_name='Ветка'),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.weapon', verbose_name='Оружие'),
        ),
    ]
