# Generated by Django 3.2.4 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_auto_20210608_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_active_skill',
            field=models.BooleanField(default=False),
        ),
    ]
