# Generated by Django 3.2.4 on 2021-06-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_skill_is_active_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='skill.weapon', verbose_name='Оружие'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
