# Generated by Django 3.2.4 on 2021-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_auto_20210608_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_has_parent',
            field=models.BooleanField(default=False),
        ),
    ]
