# Generated by Django 3.2.4 on 2021-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_skill_is_has_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltree',
            name='spent_points',
            field=models.IntegerField(default=0),
        ),
    ]
