# Generated by Django 3.2.4 on 2021-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_skilltree_spent_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name_en']},
        ),
        migrations.AddField(
            model_name='weapon',
            name='order',
            field=models.IntegerField(default=50),
        ),
    ]
