# Generated by Django 3.2.4 on 2021-06-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_auto_20210609_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['order']},
        ),
    ]
