# Generated by Django 3.2.4 on 2021-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_alter_weapon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_has_left_parent',
            field=models.BooleanField(default=False),
        ),
    ]
