# Generated by Django 3.2.4 on 2021-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='checked_skills',
            new_name='checked_skills_left',
        ),
        migrations.AddField(
            model_name='build',
            name='checked_skills_right',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
