# Generated by Django 3.2.4 on 2021-06-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_auto_20210616_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-id']},
        ),
    ]
