# Generated by Django 3.2.4 on 2021-06-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0019_weapon_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='checked_skills_left',
            new_name='checked_skills_left_w1',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='checked_skills_right',
            new_name='checked_skills_left_w2',
        ),
        migrations.RemoveField(
            model_name='build',
            name='weapon',
        ),
        migrations.AddField(
            model_name='build',
            name='checked_skills_right_w1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='checked_skills_right_w2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='total_rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='build',
            name='votes',
            field=models.IntegerField(default=1, verbose_name='Голосов'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon1', to='skill.weapon', verbose_name='Оружие'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon2', to='skill.weapon', verbose_name='Оружие'),
        ),
    ]
