# Generated by Django 3.2.4 on 2021-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0020_auto_20210623_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
