# Generated by Django 3.2.4 on 2021-07-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0021_alter_build_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min', models.IntegerField(default=5)),
                ('max', models.IntegerField(default=300)),
                ('step1_description', models.TextField(blank=True, null=True)),
                ('step1_val', models.IntegerField(default=50)),
                ('step2_description', models.TextField(blank=True, null=True)),
                ('step2_val', models.IntegerField(default=100)),
                ('step3_description', models.TextField(blank=True, null=True)),
                ('step3_val', models.IntegerField(default=150)),
                ('step4_description', models.TextField(blank=True, null=True)),
                ('step4_val', models.IntegerField(default=200)),
                ('step5_description', models.TextField(blank=True, null=True)),
                ('step5_val', models.IntegerField(default=250)),
                ('step6_description', models.TextField(blank=True, null=True)),
                ('step6_val', models.IntegerField(default=300)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BuildFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.build', verbose_name='Билд')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
    ]
