# Generated by Django 3.2.4 on 2021-07-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0022_auto_20210714_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='current_val',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='buildfeedback',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='skill.build', verbose_name='Билд'),
        ),
    ]
