# Generated by Django 3.2.4 on 2021-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0024_auto_20210714_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
