# Generated by Django 3.2.4 on 2021-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0025_build_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
        ),
    ]
