# Generated by Django 3.2.4 on 2021-07-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0027_auto_20210714_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-rating', '-created_at']},
        ),
    ]
