# Generated by Django 3.2.4 on 2021-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0028_alter_build_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
