# Generated by Django 3.2.4 on 2021-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0029_build_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='role',
            field=models.CharField(blank=True, default='Универсал', max_length=255, verbose_name='Роль '),
        ),
    ]
