# Generated by Django 3.2.4 on 2021-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0031_alter_build_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='role',
            field=models.CharField(blank=True, default='Не указана', max_length=255, verbose_name='Роль '),
        ),
    ]
